set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]


set_property PACKAGE_PIN V17 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
# VGA signals
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN K18 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN L18 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN N18 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN D17 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN G17 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN H17 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN J17 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN N19 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN J19 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN H19 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN G19 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
#led
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
#anjian
set_property PACKAGE_PIN U18 [get_ports do]
set_property IOSTANDARD LVCMOS33 [get_ports do]
set_property PACKAGE_PIN T18 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property PACKAGE_PIN U17 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property PACKAGE_PIN W19 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property PACKAGE_PIN T17 [get_ports right]
set_property IOSTANDARD LVCMOS33 [get_ports right]
#seg 7
set_property PACKAGE_PIN T1 [get_ports at2]
set_property IOSTANDARD LVCMOS33 [get_ports at2]
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {sm_db[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_db[0]}]
set_property PACKAGE_PIN W6 [get_ports {sm_db[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_db[1]}]
set_property PACKAGE_PIN U8 [get_ports {sm_db[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_db[2]}]
set_property PACKAGE_PIN V8 [get_ports {sm_db[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_db[3]}]
set_property PACKAGE_PIN U5 [get_ports {sm_db[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_db[4]}]
set_property PACKAGE_PIN V5 [get_ports {sm_db[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_db[5]}]
set_property PACKAGE_PIN U7 [get_ports {sm_db[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_db[6]}]
set_property PACKAGE_PIN U2 [get_ports {sm_cs_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_cs_n[0]}]
set_property PACKAGE_PIN U4 [get_ports {sm_cs_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_cs_n[1]}]
set_property PACKAGE_PIN V4 [get_ports {sm_cs_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_cs_n[2]}]
set_property PACKAGE_PIN W4 [get_ports {sm_cs_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_cs_n[3]}]



set_property PACKAGE_PIN C17 [get_ports PS2_CLK]
set_property PACKAGE_PIN B17 [get_ports PS2_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]

